<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Name_recipient-name</name>
   <tag></tag>
   <elementGuidId>d4a4ef91-1e11-4219-ac0e-941c9a494cec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recipient-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='recipient-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82f241b8-a189-45ec-8d13-c73006864cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64c1b1ae-f331-43f2-8a1c-2a1fed426a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>41f45f02-a9a6-45f6-9677-c0d329ed3229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recipient-name</value>
      <webElementGuid>44ddbdf7-aafe-4072-9288-f0ca4962ce47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recipient-name&quot;)</value>
      <webElementGuid>e7ef52ad-67c4-4d89-ac92-2bea084e6fc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='recipient-name']</value>
      <webElementGuid>7815b065-c75b-4ac1-94c7-cd5db17a39ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exampleModal']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>bee19846-8090-4a83-b1ff-d107ed712095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>1f104f2f-9850-4518-921b-bc97191025eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'recipient-name']</value>
      <webElementGuid>92c63fd7-b38f-45e4-91e9-fa5852cecc98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
